import { Fredoka } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/PageTransition";

const fredoka = Fredoka({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"], variable: "--font-fredoka" });

export const metadata = {
  title: "Family Battery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fredoka.className}>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
